# generated by datamodel-codegen:
#   filename:  v1.json
#   timestamp: 2026-05-23T14:24:54+00:00

from __future__ import annotations
from typing import Any
from pydantic import UUID4, AwareDatetime, BaseModel, Field


class Message(BaseModel):
    message: str = Field(..., title="Message")


class GroupSchema(BaseModel):
    group_name: str = Field(..., title="Group Name")
    group_id: int = Field(..., title="Group Id")


class ExistsMessage(BaseModel):
    message: str = Field(..., title="Message")
    document_id: UUID4 = Field(..., title="Document Id")


class DocumentSchema(BaseModel):
    title: str = Field(..., title="Title")
    doctype_name: str | None = Field(None, title="Doctype Name")
    parent_document: UUID4 | None = Field(None, title="Parent Document")
    external_id: str | None = Field(None, title="External Id")
    custom_attributes: Any = Field(None, title="Custom Attributes")
    description: str | None = Field(None, title="Description")
    write_groups: list[GroupSchema] | None = Field(None, title="Write Groups")
    read_groups: list[GroupSchema] | None = Field(None, title="Read Groups")
    visual_preferences: Any = Field(None, title="Visual Preferences")
    document_id: UUID4 = Field(..., title="Document Id")
    docstate_name: str | None = Field(None, title="Docstate Name")
    short_id: str | None = Field(None, title="Short Id")
    owner_username: str | None = Field(None, title="Owner Username")
    last_processing_task_id: UUID4 | None = Field(None, title="Last Processing Task Id")
    start_date: AwareDatetime | None = Field(None, title="Start Date")
    end_date: AwareDatetime | None = Field(None, title="End Date")
    business_partner_name: str | None = Field(None, title="Business Partner Name")
    client_legal_entity_name: str | None = Field(None, title="Client Legal Entity Name")
    filename: str | None = Field(None, title="Filename")
    can_delete: bool = Field(..., title="Can Delete")
    created_date: AwareDatetime | None = Field(None, title="Created Date")
    process_status: str | None = Field(None, title="Process Status")
    process_status_message: str | None = Field(None, title="Process Status Message")
