# generated by datamodel-codegen:
#   filename:  v2.json
#   timestamp: 2026-05-23T14:24:55+00:00
#
# MANUAL PATCHES (re-apply after regeneration):
#   - datetime added to date import (API returns naive datetimes)
#   - AwareDatetime removed from pydantic import
#   - DocListRowOut.created_date: AwareDatetime -> datetime (API omits timezone)

from __future__ import annotations
from datetime import date, datetime  # PATCH: datetime added; see note above
from enum import StrEnum
from typing import Any, Literal
from pydantic import UUID4, BaseModel, Field  # PATCH: AwareDatetime removed


class ExtractionPayloadWidgetOut(BaseModel):
    schema_name: str = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: Any = Field(..., title="Payload")
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class Message(BaseModel):
    message: str = Field(..., title="Message")


class ADL(StrEnum):
    Bathing = "Bathing"
    Continence = "Continence"
    Dressing = "Dressing"
    Eating = "Eating"
    Toileting = "Toileting"
    Transferring = "Transferring"


class BenefitPaymentKind(StrEnum):
    Indemnity = "Indemnity"
    Reimbursement = "Reimbursement"
    Not_Stated = "Not Stated"


class CitedState(StrEnum):
    EXTRACTED = "EXTRACTED"
    NORMALIZED = "NORMALIZED"
    EXTRACT_ERROR = "EXTRACT_ERROR"
    NORMALIZE_ERROR = "NORMALIZE_ERROR"
    REVIEWED = "REVIEWED"


class ConfidenceLevel(StrEnum):
    high = "high"
    medium = "medium"
    low = "low"


class CurrencyCode(StrEnum):
    USD = "USD"
    EUR = "EUR"
    AED = "AED"
    AFN = "AFN"
    ALL = "ALL"
    AMD = "AMD"
    ANG = "ANG"
    AOA = "AOA"
    ARS = "ARS"
    AUD = "AUD"
    AWG = "AWG"
    AZN = "AZN"
    BAM = "BAM"
    BBD = "BBD"
    BDT = "BDT"
    BGN = "BGN"
    BHD = "BHD"
    BIF = "BIF"
    BMD = "BMD"
    BND = "BND"
    BOB = "BOB"
    BRL = "BRL"
    BSD = "BSD"
    BTN = "BTN"
    BWP = "BWP"
    BYR = "BYR"
    BZD = "BZD"
    CAD = "CAD"
    CDF = "CDF"
    CHF = "CHF"
    CLP = "CLP"
    CNY = "CNY"
    COP = "COP"
    CRC = "CRC"
    CUC = "CUC"
    CUP = "CUP"
    CVE = "CVE"
    CZK = "CZK"
    DJF = "DJF"
    DKK = "DKK"
    DOP = "DOP"
    DZD = "DZD"
    EGP = "EGP"
    ERN = "ERN"
    ETB = "ETB"
    FJD = "FJD"
    FKP = "FKP"
    GBP = "GBP"
    GEL = "GEL"
    GGP = "GGP"
    GHS = "GHS"
    GIP = "GIP"
    GMD = "GMD"
    GNF = "GNF"
    GTQ = "GTQ"
    GYD = "GYD"
    HKD = "HKD"
    HNL = "HNL"
    HRK = "HRK"
    HTG = "HTG"
    HUF = "HUF"
    IDR = "IDR"
    ILS = "ILS"
    IMP = "IMP"
    INR = "INR"
    IQD = "IQD"
    IRR = "IRR"
    ISK = "ISK"
    JEP = "JEP"
    JMD = "JMD"
    JOD = "JOD"
    JPY = "JPY"
    KES = "KES"
    KGS = "KGS"
    KHR = "KHR"
    KMF = "KMF"
    KPW = "KPW"
    KRW = "KRW"
    KWD = "KWD"
    KYD = "KYD"
    KZT = "KZT"
    LAK = "LAK"
    LBP = "LBP"
    LKR = "LKR"
    LRD = "LRD"
    LSL = "LSL"
    LYD = "LYD"
    MAD = "MAD"
    MDL = "MDL"
    MGA = "MGA"
    MKD = "MKD"
    MMK = "MMK"
    MNT = "MNT"
    MOP = "MOP"
    MRO = "MRO"
    MUR = "MUR"
    MVR = "MVR"
    MWK = "MWK"
    MXN = "MXN"
    MYR = "MYR"
    MZN = "MZN"
    NAD = "NAD"
    NGN = "NGN"
    NIO = "NIO"
    NOK = "NOK"
    NPR = "NPR"
    NZD = "NZD"
    OMR = "OMR"
    PAB = "PAB"
    PEN = "PEN"
    PGK = "PGK"
    PHP = "PHP"
    PKR = "PKR"
    PLN = "PLN"
    PYG = "PYG"
    QAR = "QAR"
    RON = "RON"
    RSD = "RSD"
    RUB = "RUB"
    RWF = "RWF"
    SAR = "SAR"
    SBD = "SBD"
    SCR = "SCR"
    SDG = "SDG"
    SEK = "SEK"
    SGD = "SGD"
    SHP = "SHP"
    SLL = "SLL"
    SOS = "SOS"
    SPL = "SPL"
    SRD = "SRD"
    STD = "STD"
    SVC = "SVC"
    SYP = "SYP"
    SZL = "SZL"
    THB = "THB"
    TJS = "TJS"
    TMT = "TMT"
    TND = "TND"
    TOP = "TOP"
    TRY = "TRY"
    TTD = "TTD"
    TVD = "TVD"
    TWD = "TWD"
    TZS = "TZS"
    UAH = "UAH"
    UGX = "UGX"
    UYU = "UYU"
    UZS = "UZS"
    VEF = "VEF"
    VND = "VND"
    VUV = "VUV"
    WST = "WST"
    XAF = "XAF"
    XCD = "XCD"
    XDR = "XDR"
    XOF = "XOF"
    XPF = "XPF"
    YER = "YER"
    ZAR = "ZAR"
    ZMW = "ZMW"
    ZWD = "ZWD"


class DBOption(StrEnum):
    Option_A__Level_ = "Option A (Level)"
    Option_B__Increasing_ = "Option B (Increasing)"
    Level_Only = "Level Only"
    Not_Stated = "Not Stated"


class Frequency(StrEnum):
    monthly = "monthly"
    quarterly = "quarterly"
    yearly = "yearly"


class LoanRateBasis(StrEnum):
    In_Advance = "In Advance"
    In_Arrears = "In Arrears"
    Moody_Bond_Yield_Reference = "Moody Bond Yield Reference"
    Not_Stated = "Not Stated"


class MECStatus(StrEnum):
    Modified_Endowment_Contract = "Modified Endowment Contract"
    Non_MEC = "Non-MEC"
    MEC_Unless_1035_From_Non_MEC = "MEC Unless 1035 From Non-MEC"
    Not_Stated = "Not Stated"


class MoneySource(StrEnum):
    Check = "Check"
    ACH = "ACH"
    Wire = "Wire"
    field_1035_Exchange = "1035 Exchange"
    Non_Qualified_Transfer = "Non-Qualified Transfer"
    Qualified_Transfer = "Qualified Transfer"


class OrderTableRowChild(BaseModel):
    row_data: list[str] | None = Field(
        None,
        description="Cell values in this row, in column order. Empty cells should be empty strings.",
        title="Row Data",
    )
    azure_row_index: int | None = Field(
        None,
        description="Runtime annotation linking this row to an Azure DI table row.",
        title="Azure Row Index",
    )


class PremiumMode(StrEnum):
    Single_Premium = "Single Premium"
    field_5_Pay = "5 Pay"
    field_10_Pay = "10 Pay"
    Flexible_Premium = "Flexible Premium"
    Not_Stated = "Not Stated"


class ROPGuarantee(StrEnum):
    Yes___Unconditional = "Yes - Unconditional"
    Yes___Conditional = "Yes - Conditional"
    No = "No"
    Not_Stated = "Not Stated"


class RiderChargeBasis(StrEnum):
    Percent_of_Accumulation_Value = "Percent of Accumulation Value"
    Percent_of_Benefit_Base = "Percent of Benefit Base"
    Percent_of_Premium = "Percent of Premium"
    Free = "Free"
    Not_Stated = "Not Stated"


class RuleError(BaseModel):
    agent_id: str | None = Field(None, title="Agent Id")
    field: str | None = Field(None, title="Field")
    rule: str = Field(..., title="Rule")
    message: str = Field(..., title="Message")


class StateApprovalStatus(StrEnum):
    Approved = "Approved"
    Not_Approved = "Not Approved"
    Pending = "Pending"
    Product_Not_Approved = "Product Not Approved"


class StrategyKind(StrEnum):
    Fixed = "Fixed"
    Point_to_Point_Cap = "Point-to-Point Cap"
    Point_to_Point_Participation = "Point-to-Point Participation"
    Point_to_Point_Trigger = "Point-to-Point Trigger"
    Monthly_Average = "Monthly Average"
    Monthly_Point_to_Point = "Monthly Point-to-Point"
    Other = "Other"


class TableTypeEnum(StrEnum):
    CHANGE = "CHANGE"
    ORIGINAL = "ORIGINAL"
    SUMMARY = "SUMMARY"
    UNKNOWN = "UNKNOWN"


class TaxFramework(StrEnum):
    IRC_7702B = "IRC 7702B"
    IRC_101g = "IRC 101g"
    IRC_7702_ADB = "IRC 7702 ADB"
    Not_Stated = "Not Stated"


class TerminalPaymentKind(StrEnum):
    Lump_Sum_Only = "Lump Sum Only"
    Lien_Based = "Lien-Based"
    Monthly_Advances = "Monthly Advances"
    Not_Stated = "Not Stated"


class TimePeriodEnum(StrEnum):
    DAYS = "DAYS"
    WEEKS = "WEEKS"
    MONTHS = "MONTHS"
    YEARS = "YEARS"


class UnderwritingClass(StrEnum):
    Non_Tobacco = "Non-Tobacco"
    Tobacco = "Tobacco"
    Simplified_Issue = "Simplified Issue"
    Fully_Underwritten = "Fully Underwritten"
    Not_Stated = "Not Stated"


class WordMapEntry(BaseModel):
    content: str = Field(..., title="Content")
    polygon: list[float] = Field(..., title="Polygon")
    page_index: int = Field(..., title="Page Index")


class DocListRowOut(BaseModel):
    document_id: UUID4 = Field(..., title="Document Id")
    title: str | None = Field(None, title="Title")
    short_id: str | None = Field(None, title="Short Id")
    doc_type: str | None = Field(None, title="Doc Type")
    state: str = Field(..., title="State")
    created_date: datetime | None = Field(
        None, title="Created Date"
    )  # PATCH: was AwareDatetime
    owner_username: str | None = Field(None, title="Owner Username")
    process_status: str | None = Field(None, title="Process Status")
    process_status_message: str | None = Field(None, title="Process Status Message")
    start_date: date | None = Field(None, title="Start Date")
    end_date: date | None = Field(None, title="End Date")
    business_partner_id: UUID4 | None = Field(None, title="Business Partner Id")
    business_partner_name: str | None = Field(None, title="Business Partner Name")
    internal_legal_entity_id: UUID4 | None = Field(
        None, title="Internal Legal Entity Id"
    )
    internal_legal_entity_name: str | None = Field(
        None, title="Internal Legal Entity Name"
    )


class PagedDocListOut(BaseModel):
    items: list[DocListRowOut] = Field(..., title="Items")
    count: int = Field(..., title="Count")


class CompanyRefOut(BaseModel):
    id: UUID4 = Field(..., title="Id")
    canonical_name: str = Field(..., title="Canonical Name")


class DocDetailBaseOut(BaseModel):
    document_id: UUID4 = Field(..., title="Document Id")
    title: str = Field(..., title="Title")
    state: str = Field(..., title="State")
    doc_type: str | None = Field(None, title="Doc Type")
    parent_document: UUID4 | None = Field(None, title="Parent Document")
    children_docs: list[UUID4] | None = Field([], title="Children Docs")
    owner_id: int | None = Field(None, title="Owner Id")
    business_partner: CompanyRefOut | None = None
    internal_legal_entity: CompanyRefOut | None = None
    start_date: date | None = Field(None, title="Start Date")
    end_date: date | None = Field(None, title="End Date")


class CitedBool(BaseModel):
    value: bool | None = Field(None, title="Value")
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedCompanyName(BaseModel):
    value: str | None = Field(None, title="Value")
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedCurrencyCode(BaseModel):
    value: CurrencyCode | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedDate(BaseModel):
    value: date | None = Field(None, title="Value")
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedDuration(BaseModel):
    value: str | None = Field(None, title="Value")
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )
    number: int | None = Field(
        None, description="Numeric value of the period (e.g., 12).", title="Number"
    )
    unit: TimePeriodEnum | None = Field(
        None, description="Time unit: DAYS, WEEKS, MONTHS, or YEARS."
    )


class CitedFloat(BaseModel):
    value: float | None = Field(None, title="Value")
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedFrequency(BaseModel):
    value: Frequency | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedInt(BaseModel):
    value: int | None = Field(None, title="Value")
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedStr(BaseModel):
    value: str | None = Field(None, title="Value")
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedADL(BaseModel):
    value: ADL | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedBenefitPaymentKind(BaseModel):
    value: BenefitPaymentKind | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedDBOption(BaseModel):
    value: DBOption | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedLoanRateBasis(BaseModel):
    value: LoanRateBasis | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedMECStatus(BaseModel):
    value: MECStatus | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedMoneySource(BaseModel):
    value: MoneySource | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedPremiumMode(BaseModel):
    value: PremiumMode | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedROPGuarantee(BaseModel):
    value: ROPGuarantee | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedRiderChargeBasis(BaseModel):
    value: RiderChargeBasis | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedStateApprovalStatus(BaseModel):
    value: StateApprovalStatus | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedStrategyKind(BaseModel):
    value: StrategyKind | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedTableTypeEnum(BaseModel):
    value: TableTypeEnum | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedTaxFramework(BaseModel):
    value: TaxFramework | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedTerminalPaymentKind(BaseModel):
    value: TerminalPaymentKind | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CitedUnderwritingClass(BaseModel):
    value: UnderwritingClass | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )


class CreditingStrategy(BaseModel):
    strategy_name: CitedStr | None = None
    strategy_kind: CitedStrategyKind | None = None
    index_name: CitedStr | None = None
    current_cap: CitedFloat | None = None
    current_participation: CitedFloat | None = None
    current_spread: CitedFloat | None = None
    current_declared_rate: CitedFloat | None = None
    guaranteed_minimum_cap: CitedFloat | None = None
    guaranteed_minimum_participation: CitedFloat | None = None
    guaranteed_minimum_rate: CitedFloat | None = None
    index_dates: list[CitedStr] | None = Field(None, title="Index Dates")


class CriticalIllnessAccel(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    qualifying_conditions: list[CitedStr] | None = Field(
        None, title="Qualifying Conditions"
    )
    benefit_cap_pct_of_face: CitedFloat | None = None
    benefit_cap_dollar: CitedFloat | None = None
    payment_kind: CitedStr | None = None
    admin_charge: CitedFloat | None = None


class CriticalIllnessAccelPayload(BaseModel):
    schema_name: Literal["critical_illness_accel"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: CriticalIllnessAccel
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class Currency(BaseModel):
    amount: float | None = Field(None, title="Amount")
    currency: CurrencyCode | None = None


class DataTransferMeasures(BaseModel):
    datatransfer_measure: CitedStr | None = Field(
        None,
        description="A specific technical or process control in place to secure confidential information like PII as it is transferred between locations or organizations",
    )


class DataTransferMeasuresTable(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[DataTransferMeasures] = Field(
        ...,
        description="List of data transfer measures. Each row represents one protection measure.",
        title="Rows",
    )


class DataTransferMeasuresTablePayload(BaseModel):
    schema_name: Literal["data_transfer"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: DataTransferMeasuresTable
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class DeathBenefitTerms(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    face_amount_reference: CitedStr | None = None
    db_option: CitedDBOption | None = None
    db_formula: CitedStr | None = None
    mec_status: CitedMECStatus | None = None
    settlement_options: list[CitedStr] | None = Field(None, title="Settlement Options")


class DeathBenefitTermsPayload(BaseModel):
    schema_name: Literal["death_benefit_terms"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: DeathBenefitTerms
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class Discounts(BaseModel):
    discount: CitedStr | None = Field(
        None, description="A specific discount listed in the document"
    )


class DiscountsTable(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[Discounts] = Field(
        ...,
        description="List of discounts. Each discount represents a row",
        title="Rows",
    )


class DiscountsTablePayload(BaseModel):
    schema_name: Literal["discounts"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: DiscountsTable
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class DocIDs(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    contract_id: CitedStr | None = None
    circuit_id: CitedStr | None = None
    account_id: CitedStr | None = None
    order_number: CitedStr | None = None
    agreement_number: CitedStr | None = None


class DocIDsPayload(BaseModel):
    schema_name: Literal["doc_ids"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: DocIDs
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class DocumentDates(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    issue_date: CitedDate | None = None
    start_date: CitedDate | None = None
    end_date: CitedDate | None = None
    quote_end_date: CitedDate | None = None
    sign_date: CitedDate | None = None
    vendor_sign_date: CitedDate | None = None


class DocumentDatesPayload(BaseModel):
    schema_name: Literal["dates"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: DocumentDates
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class DocumentOverviewResult(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    summary: CitedStr | None = None
    solution_description: list[str] | None = Field(None, title="Solution Description")
    governing_law: CitedStr | None = None
    related_agreements: list[str] | None = Field(None, title="Related Agreements")


class DocumentOverviewResultPayload(BaseModel):
    schema_name: Literal["overview"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: DocumentOverviewResult
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class DocumentParties(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    parties: list[str] | None = Field(None, title="Parties")
    customer: CitedCompanyName | None = None
    vendor: CitedCompanyName | None = None


class DocumentPartiesPayload(BaseModel):
    schema_name: Literal["parties"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: DocumentParties
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class DocumentTimePeriod(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    term: CitedDuration | None = None
    notice_period: CitedDuration | None = None
    is_fixed_term: CitedBool | None = None
    is_perpetual: CitedBool | None = None
    is_auto_renew: CitedBool | None = None
    auto_renewal_interval: CitedDuration | None = None
    notification_period: CitedDuration | None = None
    term_for_convenience: CitedBool | None = None


class DocumentTimePeriodPayload(BaseModel):
    schema_name: Literal["term"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: DocumentTimePeriod
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class KnockoutQuestion(BaseModel):
    question_id: CitedStr | None = None
    question_text: CitedStr | None = None
    response_options: list[CitedStr] | None = Field(None, title="Response Options")
    answer_disqualifies: CitedBool | None = None
    parent_question_id: CitedStr | None = None


class KnockoutQuestions(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[KnockoutQuestion] | None = Field([], title="Rows", validate_default=True)


class KnockoutQuestionsPayload(BaseModel):
    schema_name: Literal["knockout_questions"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: KnockoutQuestions
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class LoanTerms(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    loan_rate: CitedFloat | None = None
    loan_rate_basis: CitedLoanRateBasis | None = None
    credited_rate_on_loan: CitedFloat | None = None
    loan_provisions_narrative: CitedStr | None = None


class LoanTermsPayload(BaseModel):
    schema_name: Literal["loan_terms"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: LoanTerms
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class LtcRider(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    tax_framework: CitedTaxFramework | None = None
    ltc_acceleration_factor_ref: CitedStr | None = None
    ltc_extension_multiple_ref: CitedStr | None = None
    max_monthly_ltc_benefit_formula: CitedStr | None = None
    elimination_period_days: CitedInt | None = None
    benefit_payment_kind: CitedBenefitPaymentKind | None = None
    adl_triggers: list[CitedADL] | None = Field(None, title="Adl Triggers")
    cognitive_trigger: CitedBool | None = None
    qualifying_services: list[CitedStr] | None = Field(
        None, title="Qualifying Services"
    )
    rider_charge_basis: CitedRiderChargeBasis | None = None
    waiver_of_charge_during_claim: CitedBool | None = None
    international_benefits_supported: CitedBool | None = None


class LtcRiderPayload(BaseModel):
    schema_name: Literal["ltc_rider"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: LtcRider
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class MonthlyInternetPrice(BaseModel):
    year: CitedInt | None = Field(
        None,
        description="Subscription year the monthly price applies to (1, 2, 3, ...).",
    )
    monthly_internet_price: CitedFloat | None = Field(
        None,
        description="Monthly internet price charged during this subscription year.",
    )


class NonforfeitureTerms(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    ltc_nonforfeiture_pool_formula: CitedStr | None = None
    refund_of_premium_pct: CitedFloat | None = None
    paid_up_insurance_provisions: CitedStr | None = None
    election_is_irrevocable: CitedBool | None = None
    eligibility_date_ref: CitedStr | None = None


class NonforfeitureTermsPayload(BaseModel):
    schema_name: Literal["nonforfeiture_terms"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: NonforfeitureTerms
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class OrderTableRow(BaseModel):
    row_data: list[str] | None = Field(
        None,
        description="Cell values in this row, in column order. Empty cells should be empty strings.",
        title="Row Data",
    )
    children: list[OrderTableRowChild] | None = Field(
        None,
        description="Child rows that are sub-components or nested items under this row.",
        title="Children",
    )
    azure_row_index: int | None = Field(
        None,
        description="Runtime annotation linking this row to an Azure DI table row.",
        title="Azure Row Index",
    )


class OrderTableStructure(BaseModel):
    labels: list[str] | None = Field(
        None, description="Contextual labels found near the table.", title="Labels"
    )
    headers: list[list[str]] | None = Field(
        None,
        description="Header rows of the table. Each inner list is one header row.",
        title="Headers",
    )
    body: list[OrderTableRow] | None = Field(
        None,
        description="Body rows of the table with hierarchical structure preserved.",
        title="Body",
    )


class PIIStorageLocations(BaseModel):
    pii_location: CitedStr | None = Field(
        None,
        description="An approved location for storing Personally Identifiable Information (PII)",
    )


class PIIStorageLocationsTable(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[PIIStorageLocations] = Field(
        ...,
        description="List of locations approved for storing PII in the document",
        title="Rows",
    )


class PIIStorageLocationsTablePayload(BaseModel):
    schema_name: Literal["pii_storage"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: PIIStorageLocationsTable
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class PartiesAddress(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    provider_address: CitedStr | None = None
    provider_country_code: CitedStr | None = None
    account_address: CitedStr | None = None
    account_country_code: CitedStr | None = None
    service_address: CitedStr | None = None


class PartiesAddressPayload(BaseModel):
    schema_name: Literal["address"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: PartiesAddress
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class PaymentSummary(BaseModel):
    payment_summary: CitedStr | None = Field(
        None,
        description="An individual payment instruction line item. This could be a payment term, payment summary, or billing detail",
    )


class PaymentSummaryTable(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[PaymentSummary] = Field(
        ...,
        description="List of payment terms, payment summaries, schedules, or information.",
        title="Rows",
    )


class PaymentSummaryTablePayload(BaseModel):
    schema_name: Literal["payment_summary"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: PaymentSummaryTable
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class PremiumGridRow(BaseModel):
    issue_age: CitedInt | None = None
    face_amount_band: CitedStr | None = None
    min_premium: CitedFloat | None = None
    max_premium: CitedFloat | None = None


class PremiumTerms(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    premium_mode: CitedPremiumMode | None = None
    minimum_premium: CitedStr | None = None
    maximum_premium: CitedStr | None = None
    money_source_eligibility: list[CitedMoneySource] | None = Field(
        None, title="Money Source Eligibility"
    )


class PremiumTermsPayload(BaseModel):
    schema_name: Literal["premium_terms"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: PremiumTerms
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class ProductClassification(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    chassis_kind: CitedStr | None = None
    premium_structure_signal: CitedStr | None = None
    index_linkage_signal: CitedStr | None = None
    ltc_qualification_signal: CitedStr | None = None
    funding_mechanism_signal: CitedStr | None = None
    participating_flag_signal: CitedStr | None = None


class ProductClassificationPayload(BaseModel):
    schema_name: Literal["product_classification"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: ProductClassification
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class ProductInformationComponentChild(BaseModel):
    product_name: CitedStr | None = Field(
        None, description="The product or service name."
    )
    product_description: CitedStr | None = Field(
        None, description="Description of the product or service."
    )
    product_code: CitedStr | None = Field(
        None, description="The product part number or code."
    )
    reocurring_charge: CitedFloat | None = Field(
        None, description="The Reocurring Charge (MRC)."
    )
    frequency: CitedFrequency | None = Field(
        None, description="Recurring frequency (e.g., monthly, quarterly, yearly)."
    )
    non_reocurring_charge: CitedFloat | None = Field(
        None, description="The Non Reocurring Charge (NRC)."
    )
    total_reocurring_charge: CitedFloat | None = Field(
        None, description="The total Monthly Reocurring Charge (MRC)."
    )
    total_non_reocurring_charge: CitedFloat | None = Field(
        None, description="The total Non Reocurring Charge (NRC)."
    )
    start_date: CitedStr | None = Field(
        None, description="The product, subscription, service, or warranty start date."
    )
    end_date: CitedStr | None = Field(
        None, description="The product, subscription, service, or warranty end date."
    )
    product_term: CitedStr | None = Field(
        None,
        description="Term that the product, service, or warranty is licensed for, as raw text.",
    )
    location: CitedStr | None = Field(
        None, description="The service location or delivery location."
    )
    unit_quantity: CitedStr | None = Field(
        None, description="The number of units purchased."
    )
    metric: CitedStr | None = Field(
        None,
        description="The licensing metric. Examples include processor, user, or month.",
    )
    currency: CitedStr | None = Field(
        None,
        description="ISO 4217 currency code for charge fields (e.g., USD, EUR, GBP).",
    )


class RampSchedule(BaseModel):
    name: CitedStr | None = Field(
        None, description="The name of the item impacted by the ramp schedule."
    )
    description: CitedStr | None = Field(
        None, description="Description of the item impacted by the ramp schedule."
    )
    draw_capacity: CitedStr | None = Field(
        None, description="The maximum draw capacity in the stage."
    )
    monthly_reocurring_charge: CitedFloat | None = Field(
        None, description="The base Monthly Reocurring Charge (MRC)."
    )
    max_allowed_ramp: CitedStr | None = Field(
        None, description="The base maximum allowed ramp."
    )
    ramp_percent: CitedFloat | None = Field(None, description="The ramp percentage.")
    change_start: CitedDate | None = Field(None, description="The ramp start date.")
    ramp_period: CitedInt | None = Field(
        None, description="The ramp period expressed as a number of months."
    )
    ramp_stage: CitedStr | None = Field(
        None, description="The ramp stage. Examples include stage 1 or phase 2"
    )


class ReplacementQuestion(BaseModel):
    question_id: CitedStr | None = None
    question_text: CitedStr | None = None
    response_options: list[CitedStr] | None = Field(None, title="Response Options")
    answer_captured: CitedStr | None = None


class Signatory(BaseModel):
    full_name: CitedStr | None = None
    title: CitedStr | None = None


class SignatureInfo(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    signed: CitedBool | None = None
    signatories: list[Signatory] | None = Field(None, title="Signatories")


class SignatureInfoPayload(BaseModel):
    schema_name: Literal["signature"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: SignatureInfo
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class StateApprovalRow(BaseModel):
    state_code: CitedStr | None = None
    state_name: CitedStr | None = None
    ltc: CitedStateApprovalStatus | None = None
    chronic_illness: CitedStateApprovalStatus | None = None
    terminal_illness: CitedStateApprovalStatus | None = None
    critical_illness: CitedStateApprovalStatus | None = None


class SurrenderRow(BaseModel):
    policy_year: CitedStr | None = None
    charge_percent: CitedFloat | None = None


class SurrenderSchedule(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[SurrenderRow] | None = Field([], title="Rows", validate_default=True)


class SurrenderSchedulePayload(BaseModel):
    schema_name: Literal["surrender_schedule"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: SurrenderSchedule
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class SurrenderTerms(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    surrender_charge_narrative: CitedStr | None = None
    free_withdrawal_percent: CitedFloat | None = None
    return_of_premium_guarantee: CitedROPGuarantee | None = None
    return_of_premium_conditions: CitedStr | None = None
    withdrawal_charge_schedule_ref: CitedStr | None = None


class SurrenderTermsPayload(BaseModel):
    schema_name: Literal["surrender_terms"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: SurrenderTerms
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class TableMonthlyInternetPrice(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[MonthlyInternetPrice] = Field(
        ..., description="Per-year monthly internet pricing rows.", title="Rows"
    )


class TableMonthlyInternetPricePayload(BaseModel):
    schema_name: Literal["monthly_internet_pricing"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: TableMonthlyInternetPrice
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class TableProductInformation(BaseModel):
    supplier: CitedStr | None = Field(
        None, description="The name of the supplier selling the product"
    )
    product_name: CitedStr | None = Field(
        None, description="The product or service name."
    )
    product_description: CitedStr | None = Field(
        None, description="Description of the product or service."
    )
    usage_year: CitedStr | None = Field(
        None, description="The year the software license was purchased."
    )
    license_quantity: CitedStr | None = Field(
        None, description="The number of licenses purchased."
    )
    unit_quantity: CitedStr | None = Field(
        None, description="The number of units purchased."
    )
    metric: CitedStr | None = Field(
        None,
        description="The licensing metric. Examples include processor, user, or month.",
    )
    reocurring_charge: CitedStr | None = Field(
        None, description="The Reocurring Charge (MRC)."
    )
    non_reocurring_charge: CitedStr | None = Field(
        None, description="The Non Reocurring Charge (NRC)."
    )
    total_reocurring_charge: CitedStr | None = Field(
        None, description="The total Monthly Reocurring Charge (MRC)."
    )
    total_non_reocurring_charge: CitedStr | None = Field(
        None, description="The total Non Reocurring Charge (NRC)."
    )
    location: CitedStr | None = Field(
        None, description="The location of the product, subscription, or warranty."
    )
    location_code: CitedStr | None = Field(
        None, description="A vendor specific location code associated with an address."
    )
    start_date: CitedStr | None = Field(
        None, description="The product, subscription, service, or warranty start date."
    )
    end_date: CitedStr | None = Field(
        None, description="The product, subscription, service, or warranty end date."
    )
    product_code: CitedStr | None = Field(
        None, description="The product part number or code."
    )
    product_term: CitedStr | None = Field(
        None,
        description="Term that the product, service, or warranty is licensed for (e.g., '3 years', '36 months').",
    )
    product_type: CitedStr | None = Field(
        None,
        description="The type of product or service being purchased. Examples include hardware, software license, software subscription, and warranty",
    )
    frequency: CitedFrequency | None = Field(
        None, description="Recurring frequency (e.g., monthly, quarterly, yearly)."
    )


class TableProductList(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[TableProductInformation] = Field(
        ...,
        description="Row of product information found in the purchase order.",
        title="Rows",
    )


class TableProductListPayload(BaseModel):
    schema_name: Literal["po_agent"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: TableProductList
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class TableRampSchedule(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[RampSchedule] = Field(
        ..., description="Row of ramp schedule items", title="Rows"
    )


class TableRampSchedulePayload(BaseModel):
    schema_name: Literal["ramp_schedule"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: TableRampSchedule
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class TerminalIllnessAccel(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    life_expectancy_threshold_months: CitedInt | None = None
    max_acceleration_pct_of_face: CitedFloat | None = None
    max_acceleration_dollar: CitedFloat | None = None
    min_acceleration_dollar: CitedFloat | None = None
    interest_rate_discount_cap: CitedFloat | None = None
    additional_risk_margin_cap: CitedFloat | None = None
    admin_charge_cap: CitedFloat | None = None
    payment_kind: CitedTerminalPaymentKind | None = None


class TerminalIllnessAccelPayload(BaseModel):
    schema_name: Literal["terminal_illness_accel"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: TerminalIllnessAccel
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class AOIGridRow(BaseModel):
    issue_age: CitedInt | None = None
    sex: CitedStr | None = None
    underwriting_class: CitedUnderwritingClass | None = None
    aoi_per_dollar: CitedFloat | None = None


class BuildChartRow(BaseModel):
    age: CitedInt | None = None
    height_in: CitedInt | None = None
    min_weight_lb: CitedInt | None = None
    max_weight_lb: CitedInt | None = None


class ChangePrice(BaseModel):
    table_type: CitedTableTypeEnum | None = Field(
        None,
        description="Determine if the table has a label such as Change, Summary, or Original.",
    )
    product_name: CitedStr | None = Field(
        None, description="The product or service name."
    )
    product_description: CitedStr | None = Field(
        None, description="Description of the product or service."
    )
    original_unit_quantity: CitedFloat | None = None
    updated_unit_quantity: CitedFloat | None = None
    original_monthly_reocurring_charge: CitedFloat | None = None
    original_non_reocurring_charge: CitedFloat | None = None
    original_total_monthly_reocurring_charge: CitedFloat | None = None
    original_total_non_reocurring_charge: CitedFloat | None = None
    updated_monthly_reocurring_charge: CitedFloat | None = None
    updated_non_reocurring_charge: CitedFloat | None = None
    updated_total_monthly_reocurring_charge: CitedFloat | None = None
    updated_total_non_reocurring_charge: CitedFloat | None = None


class ChronicIllnessAccel(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    tax_framework: CitedTaxFramework | None = None
    monthly_cap_percent_of_face: CitedFloat | None = None
    monthly_cap_amount: CitedFloat | None = None
    annual_cap_amount: CitedFloat | None = None
    hipaa_per_diem_referenced: CitedBool | None = None
    elimination_period_days: CitedInt | None = None
    adl_triggers: list[CitedADL] | None = Field(None, title="Adl Triggers")
    cognitive_trigger: CitedBool | None = None
    discount_rate_lump_sum: CitedStr | None = None


class ChronicIllnessAccelPayload(BaseModel):
    schema_name: Literal["chronic_illness_accel"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: ChronicIllnessAccel
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class CitedCurrency(BaseModel):
    value: Currency | None = None
    source_text: str | None = Field(
        None,
        description="Exact phrase from the document the value was extracted from.",
        title="Source Text",
    )
    page: int | None = Field(
        None,
        description="Page number (0-indexed) where source_text appears.",
        title="Page",
    )
    confidence: ConfidenceLevel | None = Field(
        None, description="Extraction confidence: high | medium | low."
    )
    state: CitedState | None = Field(
        "EXTRACTED",
        description="Lifecycle state. EXTRACTED triggers server-side coercion of source_text to typed value. NORMALIZED / REVIEWED are trusted.",
    )
    word_map: list[WordMapEntry] | None = Field(
        None, description="Resolved word positions for source_text.", title="Word Map"
    )
    amount: float | None = Field(None, description="Monetary amount.", title="Amount")
    currency_code: CurrencyCode | None = Field(
        None, description="ISO 4217 three-letter currency code."
    )


class CitedIssueAgeRange(BaseModel):
    pay_variant: CitedStr | None = None
    min_age: CitedInt | None = None
    max_age: CitedInt | None = None


class CitedRiderExclusion(BaseModel):
    rider_name: CitedStr | None = None
    state_name: CitedStr | None = None


class CreditingStrategies(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    strategies: list[CreditingStrategy] | None = Field(None, title="Strategies")


class CreditingStrategiesPayload(BaseModel):
    schema_name: Literal["crediting_strategies"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: CreditingStrategies
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class IssueEligibility(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    issue_age_ranges: list[CitedIssueAgeRange] | None = Field(
        None, title="Issue Age Ranges"
    )
    underwriting_class: CitedUnderwritingClass | None = None
    build_chart_reference: CitedStr | None = None
    expedited_underwriting_thresholds: CitedStr | None = None


class IssueEligibilityPayload(BaseModel):
    schema_name: Literal["issue_eligibility"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: IssueEligibility
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class OrderTableExtractionResult(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[OrderTableStructure] | None = Field(
        None,
        description="List of order tables extracted from the document.",
        title="Rows",
    )


class OrderTableExtractionResultPayload(BaseModel):
    schema_name: Literal["standard_product"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: OrderTableExtractionResult
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class PremiumGrid(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[PremiumGridRow] | None = Field([], title="Rows", validate_default=True)


class PremiumGridPayload(BaseModel):
    schema_name: Literal["premium_grid"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: PremiumGrid
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class PricingInfo(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    has_recurring_charges: CitedBool | None = None
    has_non_recurring_charges: CitedBool | None = None
    total_rc: CitedCurrency | None = None
    total_nrc: CitedCurrency | None = None
    frequency: CitedFrequency | None = None
    discount_description: CitedStr | None = None
    currency_code: CitedCurrencyCode | None = None
    taxes: CitedStr | None = None
    payment_terms: CitedStr | None = None


class PricingInfoPayload(BaseModel):
    schema_name: Literal["pricing"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: PricingInfo
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class ProductInformationComponent(BaseModel):
    product_name: CitedStr | None = Field(
        None, description="The product or service name."
    )
    product_description: CitedStr | None = Field(
        None, description="Description of the product or service."
    )
    product_code: CitedStr | None = Field(
        None, description="The product part number or code."
    )
    reocurring_charge: CitedFloat | None = Field(
        None, description="The Reocurring Charge (MRC)."
    )
    frequency: CitedFrequency | None = Field(
        None, description="Recurring frequency (e.g., monthly, quarterly, yearly)."
    )
    non_reocurring_charge: CitedFloat | None = Field(
        None, description="The Non Reocurring Charge (NRC)."
    )
    total_reocurring_charge: CitedFloat | None = Field(
        None, description="The total Monthly Reocurring Charge (MRC)."
    )
    total_non_reocurring_charge: CitedFloat | None = Field(
        None, description="The total Non Reocurring Charge (NRC)."
    )
    start_date: CitedStr | None = Field(
        None, description="The product, subscription, service, or warranty start date."
    )
    end_date: CitedStr | None = Field(
        None, description="The product, subscription, service, or warranty end date."
    )
    product_term: CitedStr | None = Field(
        None,
        description="Term that the product, service, or warranty is licensed for, as raw text.",
    )
    location: CitedStr | None = Field(
        None, description="The service location or delivery location."
    )
    unit_quantity: CitedStr | None = Field(
        None, description="The number of units purchased."
    )
    metric: CitedStr | None = Field(
        None,
        description="The licensing metric. Examples include processor, user, or month.",
    )
    currency: CitedStr | None = Field(
        None,
        description="ISO 4217 currency code for charge fields (e.g., USD, EUR, GBP).",
    )
    sub_component: list[ProductInformationComponentChild] | None = Field(
        None,
        description="Sub-components or child line items of this product.",
        title="Sub Component",
    )


class ReplacementDisclosure(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    questions: list[ReplacementQuestion] | None = Field(None, title="Questions")
    existing_coverage_table_ref: CitedStr | None = None
    intent_to_replace: CitedBool | None = None
    intent_to_1035_exchange: CitedBool | None = None


class ReplacementDisclosurePayload(BaseModel):
    schema_name: Literal["replacement_disclosure"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: ReplacementDisclosure
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class StateApprovalMatrix(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[StateApprovalRow] | None = Field([], title="Rows", validate_default=True)


class StateApprovalMatrixPayload(BaseModel):
    schema_name: Literal["state_approval_matrix"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: StateApprovalMatrix
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class StateAvailabilityText(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    excluded_states: list[CitedStr] | None = Field(None, title="Excluded States")
    rider_specific_exclusions: list[CitedRiderExclusion] | None = Field(
        None, title="Rider Specific Exclusions"
    )
    cross_border_sales_allowed: CitedBool | None = None


class StateAvailabilityTextPayload(BaseModel):
    schema_name: Literal["state_availability_text"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: StateAvailabilityText
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class TableChangePrice(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[ChangePrice] = Field(
        ..., description="Row of price changes from an order", title="Rows"
    )


class TableChangePricePayload(BaseModel):
    schema_name: Literal["change_price"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: TableChangePrice
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class TableSimplifiedProduct(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[ProductInformationComponent] = Field(
        ...,
        description="Row of product information found in the purchase order.",
        title="Rows",
    )


class TableSimplifiedProductPayload(BaseModel):
    schema_name: Literal["simplified_product"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: TableSimplifiedProduct
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class AOIGrid(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[AOIGridRow] | None = Field([], title="Rows", validate_default=True)
    chronic_pct: CitedInt | None = None


class AOIGridPayload(BaseModel):
    schema_name: Literal["aoi_grid"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: AOIGrid
    display_config: dict[str, Any] | None = Field({}, title="Display Config")


class BuildChart(BaseModel):
    errors: list[RuleError] | None = Field(None, title="Errors")
    rows: list[BuildChartRow] | None = Field([], title="Rows", validate_default=True)


class BuildChartPayload(BaseModel):
    schema_name: Literal["build_chart"] = Field(..., title="Schema Name")
    schema_version: str = Field(..., title="Schema Version")
    payload: BuildChart
    display_config: dict[str, Any] | None = Field({}, title="Display Config")
